### ISSUE TITLE
Problem encountered calling the OAuth Agent

### ISSUE THREAD

**Issue by berpcor** [curityio/spa-using-token-handler#25]
Mac OS, Docker Desktop (4.5.0 (74594)).
Everything done followed by instructions (https://github.com/curityio/spa-using-token-handler/blob/main/doc/Standard.md and video here - https://curity.io/resources/learn/token-handler-spa-example/), but..

Problem starts from here:
"Then browse to http://www.example.com/ and sign in with the following test user name and password:"

When I visit the link, I get:

![image](https://user-images.githubusercontent.com/1884568/177205370-9f7bb5b1-ae6a-4834-95a0-1cff84dbe5d8.png)

My hosts file:

![image](https://user-images.githubusercontent.com/1884568/177205433-0a9dfed4-1b09-4f4c-aea2-f72866446ec9.png)

![image](https://user-images.githubusercontent.com/1884568/177205552-7c494b24-b077-4374-884b-569b31e28f08.png)

Looks like local hosts file is not working or something wrong with port 80. 

I go to resources/docker-compose-standard.yml and change port to 8888:

![image](https://user-images.githubusercontent.com/1884568/177205717-b1094206-040d-4020-93ea-e8ebb070b2a5.png)

Then I run `./deploy.sh` again and ...

![image](https://user-images.githubusercontent.com/1884568/177206136-264ce902-835f-43a7-86d3-da7b46e097d1.png)

Any ideas?

**Comment by gary-archer** [comment]
Interesting - seems like it might be an issue where an online http://www.example.com conflicts with the code example in your machine's setup. You can re-run the deployment with different parameters to get up and running:

**OPTION 1 (DIFFERENT PORT)**

To run the SPA on port 8888, edit the detailed deployment script at `resources\deploy.sh' and edit this line, then browse to http:///www.example.com:8888 and the end-to-end solution will work:

```bash
if [ "$WEB_SUBDOMAIN" != "" ]; then
  WEB_DOMAIN="$WEB_SUBDOMAIN.$BASE_DOMAIN:8888"
fi
```

**OPTION 2 (DIFFERENT DOMAIN)**

To run the SPA on your own choice of domain, such as `mycompany.com`, simply edit the base domain in the root level deployment script at `deploy.sh`, then browse to http:///www.mycompany.com and the end-to-end solution will work:

```bash
export BASE_DOMAIN='mycompany.com'
```
