### ISSUE TITLE
Unable to pull the docker images

### ISSUE THREAD

**Issue by ClaudenirFreitas** [curityio/spa-using-token-handler#29]
Hi all,
I am trying to run this demo but I have been getting some errors to pull the docker images.

```
./deploy.sh
...
Error response from daemon: pull access denied for custom_kong, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Problem encountered starting Docker components
...
```

What is the docker registry?

Cheers.

**Comment by ClaudenirFreitas** [comment]
Before executing [this step](https://github.com/curityio/spa-using-token-handler/blob/main/doc/Standard.md#deploy-the-system), we should build the docker images e.g.:
```
docker build \
    --tag custom_kong:3.0.0 \
    --file resources/components/api-gateway/kong/Dockerfile \
    resources/components/api-gateway/kong/.
```

The documentation can be updated, what do you think?

**Comment by paulfrench** [comment]
Building the Kong docker image resolved the issue. This issue should be re-opened

**Comment by mtrojanowski** [comment]
@ClaudenirFreitas @paulfrench Im assuming you ran `./build.sh` before running `./deploy.sh`? The Kong image should be built in the build step. I'll have a look at that and make sure that it's actually being built in the correct way.

**Comment by paulfrench** [comment]
Yes, I followed the instructions exactly and I did run `./buid.sh` before `./deploy.sh`, for some reason the Kong image was not available and I had to manually build it as indicated by @ClaudenirFreitas , Thanks

**Comment by ClaudenirFreitas** [comment]
[This PR](https://github.com/curityio/spa-deployments/pull/38) will fix this incident.

**Comment by ClaudenirFreitas** [comment]
There is [another PR](https://github.com/curityio/spa-using-token-handler/pull/30) to improve the docs.

Feel free to review them. 😄

**Comment by gary-archer** [comment]
Thanks for your help @ClaudenirFreitas - closing this
