### ISSUE TITLE
Command in Financial doc fails

### ISSUE THREAD

**Issue by iggbom** [curityio/spa-using-token-handler#33]
In the [Troubleshoot section of Finance.md](https://github.com/curityio/spa-using-token-handler/blob/main/doc/Financial.md#troubleshoot) this command fails if the default build and deploy commands have been used.

```
export REVERSE_PROXY_CONTAINER_ID=$(docker container ls | grep reverse-proxy | awk '{print $1}')
docker logs -f $REVERSE_PROXY_CONTAINER_ID
```

The issue is `grep reverse-proxy`. There is no container with that name. Its is named something like `spa-kong-api-gateway-1`

**Comment by gary-archer** [comment]
Fixed doc
